name: random_number_generator
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^6.5.5
  get_it: ^7.2.0
  rxdart: ^0.27.7
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
